FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential g++-multilib gcc-multilib \
        libopenal-dev libpng-dev libjpeg-dev \
        libfreetype6-dev libfontconfig1-dev \
        libcurl4-gnutls-dev libsdl2-dev \
        zlib1g-dev libbz2-dev libedit-dev \
        python3 git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
